### ISSUE TITLE
Workflow run failed upon merge

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/champions#47]
https://github.com/Green-Software-Foundation/champions/actions/runs/6950336919
@osamajandali for investigation :)

**Comment by osamajandali** [comment]
This was due to the indentation. The yaml gives error as well.

Error:
![Image](https://github.com/Green-Software-Foundation/champions/assets/13832392/926cb068-ec16-4581-8bbf-6f79c3622c91)

How it should be:
![Image](https://github.com/Green-Software-Foundation/champions/assets/13832392/78bc59d6-6524-4c24-8efd-9c17ded69b7f)

**Comment by adamj89** [comment]
@LieneKal just checking you've seen this for the next batch of updates. Seems the indentation breaks things.
